version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MINIO_ENDPOINT=minio:9000
    entrypoint: [ "python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001" ]
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopw123
    volumes:
      - './minio_data:/bitnami/minio/data'
    networks:
      - app-network

volumes:
  minio_data:

networks:
  app-network:
    driver: bridge